=== FaceFTW/faceftw.github.io/src/assets/json/resume.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "/resume.schema.json",
	"title": "Resume",
	"description": "Serves as a way to easily edit the resume on the portfolio without editing the HTML content",
	"type": "object",
	"properties": {
		"highlights": {
			"description": "A list of 3 highlights that are seen at the top of the resume page",
			"type": "array",
			"items": { "type": "object", "$ref": "#/$defs/highlightItem" },
			"uniqueItems": true,
			"minItems": 3,
			"maxItems": 3
		},
		"skills": {
			"description": "Represents the skills shown on the resume",
			"type": "array",
			"items": { "type": "object", "$ref": "#/$defs/skillCategory" },
			"minItems": 1,
			"uniqueItems": true
		},
		"education": {
			"description": "Represents the education on the resume",
			"type": "array",
			"items": { "type": "object", "$ref": "#/$defs/eduExperience" },
			"minItems": 1,
			"uniqueItems": true
		},
		"experience": {
			"description": "Represents the Job Experience shown on the resume",
			"type": "array",
			"items": { "type": "object", "$ref": "#/$defs/profExperience" },
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"$defs": {
		"highlightItem": {
			"description": "Defines one of the three \"highlights\" on top of the resume page",
			"type": "object",
			"properties": {
				"icon": {
					"description": "The icon used for this highlight. See https://www.nerdfonts.com/cheat-sheet for a list of available symbols",
					"type": "string"
				},
				"stat": {
					"description": "The statistic used for the highlight",
					"type": "string"
				},
				"statDescription": {
					"description": "A description for the statistic in the highlight",
					"type": "string"
				},
				"required": ["icon", "stat", "statDescription"]
			}
		},
		"skillCategory": {
			"description": "Represents a category for skills",
			"type": "object",
			"properties": {
				"categoryName": {
					"description": "Name of the skill category",
					"type": "string"
				},
				"highSkill": {
					"description": "List of skills withing the category with advanced knowledge",
					"type": "array",
					"items": { "type": "string" },
					"minItems": 1,
					"uniqueItems": true
				},
				"medSkill": {
					"description": "List of skills withing the category with intermediate knowledge",
					"type": "array",
					"items": { "type": "string" },
					"minItems": 1,
					"uniqueItems": true
				},
				"lowSkill": {
					"description": "List of skills withing the category with beginner knowledge",
					"type": "array",
					"items": { "type": "string" },
					"minItems": 1,
					"uniqueItems": true
				}
			},
			"required": ["categoryName", "lowSkill"]
		},
		"eduExperience": {},
		"profExperience": {
			"description": "This is an entry for profesional experience (e.g. a job/internship)",
			"type": "object",
			"properties": {}
		}
	}
}

=== FaceFTW/faceftw.github.io/src/assets/json/resume.json
{
	"$schema": "./resume.schema.json",
	"highlights": [
		{
			"icon": "fa-book",
			"stat": "11+ years",
			"statDescription": "Learning & Experience in Tech"
		},
		{
			"icon": "fa-github",
			"stat": "10+ Repos",
			"statDescription": "Available on Github"
		},
		{
			"icon": "fa-heart",
			"stat": "1000+ hours",
			"statDescription": "Effort, Dedication, and Learning"
		}
	],
	"skills": [
		{
			"categoryName": "Computer Programming/Software Engineering",
			"lowSkill": [
				"Graphics Programming (OpenGL Legacy)"
			],
			"medSkill": [
				"SQL Database and Queries (PostgreSQL/Microsoft SQL Server)",
				"Windows and Linux/UNIX Kernels and Environments",
				"Low-Level Programming and Processor Architecture",
				"Scripting/Automation (with Powershell/Bash)",
				"Git Version Control",
				"Continuous Integration/Continuous Deployment (CI/CD) via GitHub Actions",
				"Full-Stack Web Development"
			],
			"highSkill": [
				"Software Testing Automation",
				"Software Design and Architecture",
				"Industry-Standard Languages, including C, C++, C#, and Java",
				"Web Design (HTML5, CSS3, Javascript/Typescript)",
				"Web Application Frameworks (Angular, ReactJS (w/ Redux), NodeJS)",
				".NET and .NET Extensions (ASP.NET, Entity Framework, LINQ)",
				"Systems Programming with Rust"
			]
		},
		{
			"categoryName": "Computer Hardware/Repair",
			"lowSkill": [
				"Electronic Component Form Factors, Functions, and Use Cases"
			],
			"medSkill": [
				"IoT Devices and Architecture",
				"Arduino",
				"Raspberry Pi",
				"Data Recovery and Old Hardware Refurbishment"
			],
			"highSkill": [
				"Computer Internals and Hardware"
			]
		}
	],
	"education": [
		{
			"name": "Rose-Hulman Institute of Technology",
			"graduationDate": "BS Software Engineering - Class of 2023 (Summer)",
			"degree": [
				"Bachelors of Science - Software Engineering"
			],
			"degreeAddendum": "Originally Studied Computer Engineering until Spring 2021",
			"relCoursework": [
				"Intro to Computer Systems (CSSE132)",
				"Intro to Embedded Systems (ECE230)",
				"Intro to Object Oriented Programming (CSSE220)",
				"Data Structures and Algorithms (CSSE230)",
				"Computer Architecture I (CSSE232)",
				"Intro to Database Systems (CSSE333)",
				"Software Project Management (CSSE372)",
				"Formal Methods (CSSE373)",
				"Software Design (CSSE374)",
				"Software Construction and Evolution (CSSE375)",
				"Operating Systems (CSSE332)",
				"CSSE Senior Capstone Project (CSSE497-499)"
			]
		},
		{
			"name": "Walt Whitman High School",
			"degree": [
				"High School Diploma"
			],
			"degreeAddendum": "Maryland Seal of Bi-Literacy (Chinese)",
			"graduationDate": "Class of 2019",
			"gpa": {
				"unweighted": 3.31,
				"weighted": 4.0
			},
			"relCoursework": [
				"AP Computer Science",
				"AP Calclus AB",
				"PLTW Digital Electronics",
				"PLTW Engineering Design and Development Capstone Course"
			]
		}
	],
	"experience": [
		{
			"name": "Comcast",
			"position": "Software Engineer II (Contractor)",
			"timeEmployed": "August 2023 - Present",
			"location": "Washington, DC",
			"responsibilities": [
				"Designed and Implemented novel automation tools in Rust for monitoring changes in end-user behavior",
				"Created focused test cases for component testing in a voice-recognition software stack",
				"Improved existing external-facing documentation and other automations to be more detail-oriented and concise",
				"Communicated with stakeholders and teams owning dependency services to perform integration testing and clarify desired functionality",
				"Helped identify/fix bugs and implement best practices in testing tools written with Java Spring"
			]
		},
		{
			"name": "Rose Hulman CSSE Department",
			"position": "Teaching Assistant/Grader (CSSE374 - Software Design)",
			"timeEmployed": "November 2022 - June 2023",
			"location": "Terre Haute, IN",
			"responsibilities": [
				"Graded and provided feedback on student's code in assignments ",
				"Answered students questions related to software design and the course material",
				"Provided insights into proper design and coding practices",
				"Assisted professor in facilitating in-class activities"
			]
		},
		{
			"name": "Direct Supply",
			"position": "Software Engineer Intern",
			"timeEmployed": "June 2022-August 2022",
			"location": "Milwaukee, WI",
			"responsibilities": [
				"Acted as a working member of a devlopment team to accomplish sprint goals",
				"Implemented and performed end-to-end testing of new features",
				"Coordinated and verified releases of new features/system changes",
				"Helped refine and plan user stories for future sprints",
				"Performed changes that served as maintenance tasks for system reliability",
				"Communicated changes with stakeholders and product owners"
			]
		},
		{
			"name": "Rizkly Inc.",
			"position": "Software Development Intern",
			"timeEmployed": "June 2020 - June 2022",
			"location": "Bethesda, MD",
			"responsibilities": [
				"Helped plan and suggest new algorithms to deploy for client use",
				"Wrote and optimized new algorithm code for database backends to implement new features",
				"Communicated with database/server administrators about integration of new feature-sets",
				"Documented work for company transparency to clients",
				"Implemented a CRUD-like web service that communicates with a PostgreSQL database",
				"Created Algorithm Visualizations powered by Angular"
			]
		},
		{
			"name": "Holton Arms Creative Summer",
			"position": "Web Desgin Counselor",
			"timeEmployed": "June 2019 - August 2019",
			"location": "Bethesda, MD",
			"responsibilities": [
				"Taught children ages 8-15 various principles of basic web design including HTML5 and CSS3",
				"Supervised and engaged children throughout camp day",
				"Communicated with parents about child's experiences at camp",
				"Aided with camp-related activities and duties"
			]
		}
	]
}
